# Generated by Django 3.2 on 2022-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='answers',
            field=models.TextField(max_length=250),
        ),
    ]
