# Generated by Django 3.2 on 2022-03-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О компании ', 'verbose_name_plural': 'О компании'},
        ),
    ]
