# Generated by Django 3.2 on 2022-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220310_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'About company',
                'verbose_name_plural': 'about companies',
            },
        ),
    ]
