# Generated by Django 3.2 on 2022-03-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_aboutcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCompany',
        ),
    ]
